### ISSUE TITLE
[BUG] Lambda support is not working as expected.

### ISSUE THREAD

**Issue by maheshpatil2021** [autogluon/autogluon#1630]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
 https://github.com/awslabs/autogluon/issues/921 mentions that autogluon is now supported on aws lambda. But my testing with autugluon-0.4.0 hits the same issues. i.e. it does not work in aws lambda

**Expected behavior**
 autogluon should run on lambda as mentioned here. https://auto.gluon.ai/stable/tutorials/cloud_fit_deploy/cloud-aws-lambda-deployment.html

**To Reproduce**
Here is my Dockerfile.
```
FROM public.ecr.aws/lambda/python:3.9

RUN yum install libgomp git -y \
 && yum clean all -y && rm -rf /var/cache/yum

ARG TORCH_VER=1.9.1+cpu
ARG TORCH_VISION_VER=0.10.1+cpu
ARG NUMPY_VER=1.19.5
RUN python3.9 -m pip --no-cache-dir install --upgrade --trusted-host pypi.org --trusted-host files.pythonhosted.org pip \
 && python3.9 -m pip --no-cache-dir install --upgrade wheel setuptools \
 && python3.9 -m pip uninstall -y dataclasses \
 && python3.9 -m pip --no-cache-dir install --upgrade torch=="${TORCH_VER}" torchvision=="${TORCH_VISION_VER}" -f https://download.pytorch.org/whl/torch_stable.html \
 && python3.9 -m pip --no-cache-dir install --upgrade numpy==${NUMPY_VER} \
 && python3.9 -m pip --no-cache-dir install --upgrade autogluon

RUN yum install mesa-libGL -y

COPY ./ ./
CMD ["api.lambda_handler"]
```

There are a couple of changes from the tutorial. 
1. I installed full autogluon as I was trying to test the ImagePredictor
2. I had to add RUN yum install mesa-libGL -y as without it I ran into another error. [ERROR] Runtime.ImportModuleError: Unable to import module 'api': libGL.so.1: cannot open shared object file: No such file or directory

**Screenshots**

**Installed Versions**
autogluon-0.4.0
```
docker run --rm -it --entrypoint /bin/sh  5cb9134f9414
sh-4.2# 
sh-4.2# 
sh-4.2# python
Python 3.9.11 (main, Mar 18 2022, 17:30:17) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autogluon.core.utils import show_versions
>>> show_versions()

INSTALLED VERSIONS
------------------
date                 : 2022-03-26
time                 : 19:45:27.569840
python               : 3.9.11.final.0
OS                   : Linux
OS-release           : 5.13.0-1017-aws
Version              : #19~20.04.1-Ubuntu SMP Mon Mar 7 12:53:12 UTC 2022
machine              : x86_64
processor            : x86_64
num_cores            : 2
cpu_ram_mb           : 7849
cuda version         : None
num_gpus             : 0
gpu_ram_mb           : []
avail_disk_size_mb   : 39439

autogluon.common     : 0.4.0
autogluon.core       : 0.4.0
autogluon.features   : 0.4.0
autogluon.tabular    : 0.4.0
autogluon.text       : 0.4.0
autogluon.vision     : 0.4.0
autogluon_contrib_nlp: None
boto3                : 1.21.27
catboost             : 1.0.4
dask                 : 2021.11.2
distributed          : 2021.11.2
fairscale            : 0.4.6
fastai               : 2.5.5
gluoncv              : 0.11.0
lightgbm             : 3.3.2
matplotlib           : 3.5.1
networkx             : 2.7.1
nptyping             : 1.4.4
numpy                : 1.22.3
omegaconf            : 2.1.1
pandas               : 1.3.5
PIL                  : 9.0.1
psutil               : 5.8.0
pytorch_lightning    : 1.5.10
ray                  : 1.8.0
requests             : 2.27.1
scipy                : 1.7.3
sentencepiece        : None
skimage              : 0.19.2
sklearn              : 1.0.2
smart_open           : 5.2.1
timm                 : 0.5.4
torch                : 1.9.1+cpu
torchmetrics         : 0.7.3
tqdm                 : 4.63.1
transformers         : 4.16.2
xgboost              : 1.4.2

```

The error that I get inside the lambda

```
[ERROR] OSError: [Errno 38] Function not implemented Traceback (most recent call last):   
File "/var/task/api.py", line 148, in lambda_handler     rtn = task.handleTask(event, context)   
File "/var/task/task.py", line 85, in handleTask     return runAutoML(event, modelMeta)   
File "/var/task/task.py", line 59, in runAutoML     result = predictor.predict(img
File)   
File "/var/lang/lib/python3.9/site-packages/autogluon/vision/predictor/predictor.py", line 579, in predict     proba = self._classifier.predict(data)   
File "/var/lang/lib/python3.9/site-packages/gluoncv/auto/estimators/base_estimator.py", line 199, in predict     return self._predict(x, **kwargs)   
File "/var/lang/lib/python3.9/site-packages/gluoncv/auto/estimators/torch_image_classification/torch_image_classification.py", line 631, in _predict     return self._predict((x,), **kwargs).drop(columns=['image'], errors='ignore')    
File "/var/lang/lib/python3.9/site-packages/gluoncv/auto/estimators/torch_image_classification/torch_image_classification.py", line 655, in _predict     for input, _ in loader:
File "/var/lang/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 354, in __iter__     self._iterator = self._get_iterator()   
File "/var/lang/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator     return _MultiProcessingDataLoaderIter(self)   
File "/var/lang/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 891, in __init__     self._worker_result_queue = multiprocessing_context.Queue() # type: ignore[var-annotated]   
File "/var/lang/lib/python3.9/multiprocessing/context.py", line 103, in Queue     return Queue(maxsize, ctx=self.get_context())   
File "/var/lang/lib/python3.9/multiprocessing/queues.py", line 43, in __init__     self._rlock = ctx.Lock()   
File "/var/lang/lib/python3.9/multiprocessing/context.py", line 68, in Lock     return Lock(ctx=self.get_context())   
File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)   
File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__     sl = self._semlock = _multiprocessing.SemLock(
```

**Comment by gradientsky** [comment]
This is not possible to fix inside AutoGluon until it's fixed in GluonCV: https://github.com/dmlc/gluon-cv/issues/1633

**Comment by gradientsky** [comment]
In the nutshell the issue is that lambda doesn't have `/dev/shm/' shared memory mount. Torch dataloaders use it to speed-up processing. The workaround is to sent `num_workers=0` into the dataloader. Last time I looked at the problem there was now way to pass it into gluoncv. @bryanyzhu FYI

**Comment by Innixma** [comment]
Marking as resolved given v0.7 has removed autogluon.vision. Please create a new issue if problems persist when using autogluon.multimodal in pre-release or v0.7+.

**Comment by Alex-Wenner-FHR** [comment]
I know this has since been closed and marked as complete (which is awesome), but I am not sure I understand the work around... @gradientsky or @Innixma could you elaborate more on this? I am using 0.6.2 Tabular Predictor and seeing this issue within my container. I would really like to have a workaround ready so that we can get this fixed up prior to 0.7!
