### ISSUE TITLE
[BUG] Windows: Fails if train path is on different drive than current directory or .venv

### ISSUE THREAD

**Issue by 2-5** [autogluon/autogluon#3325]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
After upgrading to 0.8.0, training fails if the train folder is set on a different drive than the run directory.

**Expected behavior**
Works

**To Reproduce**
```python
from autogluon.tabular import TabularDataset, TabularPredictor

train_path = "G:\\Train"  # directory on a different drive than virtual env
train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
predictor = TabularPredictor(path=train_path, label='class').fit(train_data=train_data, time_limit=60)
```

**Screenshots / Logs**
```python
Cell In[3], line 3
----> 3 predictor = TabularPredictor(path=train_path, label='class').fit(train_data=train_data, time_limit=60)

File .venv\lib\site-packages\autogluon\core\utils\decorators.py:30, in unpack.._unpack_inner.._call(*args, **kwargs)
     27 @functools.wraps(f)
     28 def _call(*args, **kwargs):
     29     gargs, gkwargs = g(*other_args, *args, **kwargs)
---> 30     return f(*gargs, **gkwargs)

File .venv\lib\site-packages\autogluon\tabular\predictor\predictor.py:951, in TabularPredictor.fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, feature_metadata, infer_limit, infer_limit_batch_size, fit_weighted_ensemble, calibrate_decision_threshold, num_cpus, num_gpus, **kwargs)
--> 951 self._learner.fit(X=train_data, X_val=tuning_data, X_unlabeled=unlabeled_data,

File .venv\lib\site-packages\autogluon\tabular\learner\abstract_learner.py:131, in AbstractTabularLearner.fit(self, X, X_val, **kwargs)
--> 131 return self._fit(X=X, X_val=X_val, **kwargs)

File .venv\lib\site-packages\autogluon\tabular\learner\default_learner.py:122, in DefaultLearner._fit(self, X, X_val, X_unlabeled, holdout_frac, num_bag_folds, num_bag_sets, time_limit, infer_limit, infer_limit_batch_size, verbosity, **trainer_fit_kwargs)
--> 122 trainer = self.trainer_type(
    123     path=self.model_context,

File .venv\lib\site-packages\autogluon\core\trainer\abstract_trainer.py:60, in AbstractTrainer.__init__(self, path, problem_type, eval_metric, num_classes, quantile_levels, low_memory, feature_metadata, k_fold, n_repeats, sample_weight, weight_evaluation, save_data, random_state, verbosity)
---> 60     self.path = PathConverter.to_relative(self.path)

File .venv\lib\site-packages\autogluon\common\utils\path_converter.py:56, in PathConverter.to_relative(path)
     55 os_path_sep = PathConverter.os_path_sep()
---> 56 path_relative = os.path.relpath(path)

File lib\ntpath.py:744, in relpath(path, start)
    743 if normcase(start_drive) != normcase(path_drive):
--> 744     raise ValueError("path is on mount %r, start on mount %r" % (
    745         path_drive, start_drive))

ValueError: path is on mount 'G:', start on mount 'H:'
```

**Installed Versions**

<details>

```python

INSTALLED VERSIONS
------------------
python              : 3.10.8.final.0
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64

autogluon           : None
autogluon.common    : 0.8.0
autogluon.core      : 0.8.0
autogluon.features  : 0.8.0
autogluon.tabular   : 0.8.0
boto3               : 1.26.155
catboost            : 1.2
fastai              : 2.7.12
hyperopt            : 0.2.7
imodels             : None
lightgbm            : 3.3.5
matplotlib          : 3.7.1
networkx            : 3.1
numpy               : 1.25.0
onnxruntime-gpu     : None
pandas              : 1.5.3
psutil              : 5.9.5
ray                 : 2.3.1
requests            : 2.31.0
scikit-learn        : 1.2.2
scikit-learn-intelex: 2023.1.1
scipy               : 1.10.1
setuptools          : 67.8.0
skl2onnx            : None
tabpfn              : 0.1.9
torch               : 1.13.1+cu117
tqdm                : 4.65.0
vowpalwabbit        : None
xgboost             : 1.7.5
```

</details>

**Comment by 2-5** [comment]
Seems to be caused by #3288

**Comment by Innixma** [comment]
Bah, these file system edge cases are brutal! Thanks for making the issue, we will try to fix by next release.

Refer to #3260 for progress updates, as the refactor should fix this issue.

**Comment by yinweisu** [comment]
Should be fixed by: https://github.com/autogluon/autogluon/pull/3355

**Comment by rokopi-byte** [comment]
This is still happening to me, `ValueError: path is on mount 'C:', start on mount 'E:'` but interestingly only if you provide `presets` to `fit`. Solution is to set the current path to E:\<path> .. not very nice..

**Comment by Creative-Ataraxia** [comment]
> This is still happening to me, `ValueError: path is on mount 'C:', start on mount 'E:'` but interestingly only if you provide `presets` to `fit`. Solution is to set the current path to E:<path> .. not very nice..
hi, how did you set the current path to E:?

**Comment by rokopi-byte** [comment]
> > This is still happening to me, `ValueError: path is on mount 'C:', start on mount 'E:'` but interestingly only if you provide `presets` to `fit`. Solution is to set the current path to E: .. not very nice..
> 
> hi, how did you set the current path to E:?

I simply put my code in E: and launching from there..
